id: I20CC4F59
legacy_id: P009311
ocr_import_info:
  bdrc_scan_id: W1KG20709
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T11:44:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:27:54.275819+00:00'
last_modified: 2022-08-31 18:28:01.537054
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG20709
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG20709
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟབ་ཁྲིད་ཀུན་བཏུས་མན་ངག་བྱིན་རླབས་ཆུ་གཏེར།
  author: གཙང་མཁན་ཆེན་དཔལ་ལྡན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8303881134937728
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I1KG20793:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG20793
      total_pages: 120
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG20793.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.8303881134937728
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
