id: I20CC4F59
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:44:46+00:00'
last_modified: '2022-06-08T10:07:00.524897+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG20709
  title: ཟབ་ཁྲིད་ཀུན་བཏུས་མན་ངག་བྱིན་རླབས་ཆུ་གཏེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    122D:
      image_group_id: I1KG20793
      title: ''
      total_pages: 120
      order: 1
      base_file: 122D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
